### PR TITLE
WIP: Switch to Ansible

### PR DESCRIPTION
**Pull request by shellt0pia**
This is the biggest change since the inception of this repository.  
I've had this on my roadmap for a long time now and after learning Ansible at work I was finally ready to jump, so I did.

More than 100 commits later and here we are. This is still a work in progress, I still have some bugs to iron out and the Transmission role is not completely working.

As soon as everything is ready I will post a migration guide here because there's some little changes here and there that will need to be dealt with before migrating.

Here's an exhaustive list of what's left to do (I will add more as time goes on):

- [x] Rename `docker-host` to `services-host` in inventories and Vagrantfile.
- [x] Rename `docker_backup` to `containers_data` in rsyncd configuration file.
- [x] Add default variables in separate folder instead of inline in roles.
- [ ] Add tagged tasks in each services role to update and restart the containers.
- [ ] Remove all encrypted variables from the roles `vars` folders and put them in the `host_vars` file or find a way with Jinja "default" beavior.
- [ ] Make OpenVPN conf file optional in Transmission role.
- [ ] Add docker prune task somewhere.
- [ ] Remove the `rsync_export_all_ro` seboolean and find an alternative solution.

### CODE REVIEW

**Comment by guillaumebriday** [comment]
Could you please merge this PR anytime soon? thanks

**Comment by shellt0pia** [comment]
> Could please merge this PR anytime soon? thanks

Could you please learn to speak English properly anytime soon ? thanks 🙃

**Comment by guillaumebriday** [comment]
I mean come on this PR has been opened for over a year now. 🙃 Please, is OSS a joke to you?

**Comment by shellt0pia** [comment]
> I mean come on this PR has been opened for over a year now. 🙃 Please, is OSS a joke to you?

And you what have you done? A measly 1.2k stars on a PHP repo, I mean I got at least 30 stars here so get on my level scrub 🙃

**Comment by guillaumebriday** [comment]
Is this PR dead? 🤔

**Comment by shellt0pia** [comment]
This branch has been superseded by the `switch-to-ansible-ng` branch which contains the code I'm running in "production" right now. It still needs a bit of work and a README revamp but I'm closing this PR in the meantime.

**Pull request closed without merging**
